site_name: SDS-Framework
repo_url: https://github.com/ARM-software/SDS-Framework
edit_uri: ./edit/main/documentation
nav:
    - Home: index.md
    - Overview: overview.md
    - SDS Template Application: template.md
    - SDSIO Interface: sdsio.md
    - Utilities: utilities.md
    - Theory of Operation: theory.md
    - API Modules: SDS_API/modules.md

plugins:
    - search
    - mermaid2    # pip install mkdocs-mermaid2-plugin
    - mkdoxy:     # pip install mkdoxy
        projects:
          SDS_API:
            src-dirs: ./sds/include
            full-doc: true
            doxy-cfg:
              FILE_PATTERNS: "*.h *.txt"
              CASE_SENSE_NAMES: YES     # Ensure case is preserved in output names
              FILE_NAME_CASE: PRESERVE  # Newer option; PRESERVE keeps case, LOWER changes all to lowercase

theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
docs_dir: documentation
site_dir: docs
use_directory_urls: false
